version: '3.8'

services:
  snpe-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./qual:/app/qual
      - ./models:/app/models
      - ./output:/app/output
    ports:
      - "8000:8000"  # For future web interface
    command: tail -f /dev/null  # Keep the container running